# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:

  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CI/CD"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CI/CD"
