"BitBar plugin":
  - meta_package_manager/bitbar/*
  - meta_package_manager/tests/*bitbar*

"CI/CD":
  - .github/**/*
  - .gitignore
  - pyproject.toml
  - setup.cfg

documentation:
  - docs/**/*
  - .mailmap
  - LICENSE
  - README.rst
  - readthedocs.yaml

"manager: apm":
  - meta_package_manager/managers/apm*
  - meta_package_manager/tests/*apm*

"manager: brew":
  - meta_package_manager/managers/homebrew*
  - meta_package_manager/tests/*homebrew*

"manager: cask":
  - meta_package_manager/managers/homebrew*
  - meta_package_manager/tests/*homebrew*

"manager: composer":
  - meta_package_manager/managers/composer*
  - meta_package_manager/tests/*composer*

"manager: dpkg-like":
  - meta_package_manager/managers/apt*
  - meta_package_manager/managers/dpkg*
  - meta_package_manager/managers/opkg*
  - meta_package_manager/tests/*apt*
  - meta_package_manager/tests/*dpkg*
  - meta_package_manager/tests/*opkg*

"manager: flatpak":
  - meta_package_manager/managers/flatpak*
  - meta_package_manager/tests/*flatpak*

"manager: gem":
  - meta_package_manager/managers/gem*
  - meta_package_manager/tests/*gem*

"manager: mas":
  - meta_package_manager/managers/mas*
  - meta_package_manager/tests/*mas*

"manager: mpm":
  - meta_package_manager/*

"manager: npm-like":
  - meta_package_manager/managers/npm*
  - meta_package_manager/managers/yarn*
  - meta_package_manager/tests/*npm*
  - meta_package_manager/tests/*yarn*

"manager: pip":
  - meta_package_manager/managers/pip*
  - meta_package_manager/tests/*pip*

"manager: snap":
  - meta_package_manager/managers/snap*
  - meta_package_manager/tests/*snap*
