name: Labeller (content-based)
on:
  issues:
    types: [opened]
  pull_request:
    typed: [opened]

jobs:
  labeller:
    name: Issue & PR labeller based on content
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.1
        with:
          parameters: >
            [
              {"labels":    ["BitBar plugin", "platform: macOS"],
               "keywords":      ["bitbar"]},

              {"labels":    ["bug"],
               "keywords":      ["bug", "error", "traceback"]},

              {"labels":    ["CI/CD"],
               "keywords":      ["ci-cd", "cicd", "ci", ".github", "workflow", "actions"]},

              {"labels":    ["documentation"],
               "keywords":      ["sphinx", "readthedocs", "read the docs", "readme", "rst", "typo"]},

              {"labels":    ["enhancement"],
               "keywords":      ["add"]},

              {"labels":    ["help wanted"],
               "keywords":      ["help"]},

               {"labels":   ["manager: apm", "platform: Linux", "platform: macOS", "platform: Windows"],
               "keywords":      ["apm", "atom"]},

              {"labels":    ["manager: brew", "platform: macOS"],
               "keywords":      ["brew", "homebrew", "tap", "formula"]},

              {"labels":    ["manager: cask", "platform: macOS"],
               "keywords":      ["cask"]},

              {"labels":    ["manager: composer", "platform: Linux", "platform: macOS", "platform: Windows"],
              "keywords":       ["composer", "php"]},

              {"labels":    ["manager: dpkg-like", "platform: Linux"],
               "keywords":      ["apt", "aptitude", "dpkg", "opkg"]},

              {"labels":    ["manager: flatpak", "platform: Linux"],
               "keywords":      ["flatpak", "flat"]},

              {"labels":    ["manager: gem", "platform: Linux", "platform: macOS", "platform: Windows"],
               "keywords":      ["gem", "ruby"]},

              {"labels":    ["manager: mas", "platform: macOS"],
               "keywords":      ["mas", "app store", "app-store"]},

              {"labels":    ["manager: npm-like", "platform: Linux", "platform: macOS", "platform: Windows"],
               "keywords":      ["npm", "node", "yarn"]},

              {"labels":    ["manager: pip", "platform: Linux", "platform: macOS", "platform: Windows"],
               "keywords":      ["pip"]},

              {"labels":    ["manager: snap", "platform: Linux"],
               "keywords":      ["snap"]},

              {"labels":    ["platform: Linux"],
               "keywords":      ["linux", "ubuntu", "debian"]},

              {"labels":    ["platform: macOS"],
               "keywords":      ["macos", "mac os", "osx", "os x", "apple"]},

              {"labels":    ["platform: Windows"],
               "keywords":      ["windows", "c:", "microsoft"]}
            ]
          github-token: ${{ secrets.GITHUB_TOKEN }}
