name: Lint
on:
  push:
    # QA on master is too late: we shouldn't mess with the code at this point.
    branches-ignore:
      - 'master'
  pull_request:

jobs:

  lint-python:
    name: Lint and check Python code
    # No need to lint before the auto formatting did its job.
    needs: format-python
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-python@v2
    - name: Install linters
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
    - name: Lint
      run: |
        poetry run pycodestyle
        poetry run pylint meta_package_manager

  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: actions/setup-python@v2
    - name: Install linter
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
    - name: Lint
      run: |
        poetry run yamllint -d relaxed .
