---
name: Lint
"on":
  push:
    branches-ignore:
      # Skip linting on prepare-release branch as it points to a tagged URL that does not exist yet.
      - prepare-release

jobs:

  lint:
    uses: kdeldycke/workflows/.github/workflows/lint.yaml@v0.7.16
