---
name: Release
"on":
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  release:
    uses: kdeldycke/workflows/.github/workflows/release.yaml@v0.4.7
    with:
      github-release-body: |
        [🐍 Available on PyPi](https://pypi.org/project/meta-package-manager/${{
        needs.git-tag.outputs.tagged_version }}/)


  build:
    name: Build, check and publish package after release
    needs: release
    runs-on: ubuntu-20.04
    steps:
      - name: Print version
        run: |
          echo "Tagged version: ${{ needs.release.outputs.tagged_version }}"
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.1
      - name: Build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install --no-interaction --no-ansi
          poetry build --no-interaction --no-ansi
      - name: Attach packages to workflow run for later inspection and debugging
        uses: actions/upload-artifact@v2.3.1
        with:
          name: mpm-python-packages
          path: ./dist/*
      - name: Validates package metadata
        run: |
          poetry check --no-interaction --no-ansi
          poetry run twine check ./dist/*
          poetry run check-wheel-contents ./dist/*.whl
      - name: Test publishing
        run: |
          poetry publish --dry-run --no-interaction
      - name: Push package to public PyPi repository
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
