---
name: Build & release
"on":
  push:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  release:
    uses: kdeldycke/workflows/.github/workflows/release.yaml@v0.7.24
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}